title: Mark Blokpoel
description: Mark's personal academic website. 

url: https://markblokpoel.com
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /
    - title: Publications
      url: /publications
    - title: Supervision and mentoring
      url: /supervision
    - title: Contact
      url: /contact

